server:
  port: 8080
jwt:
  secret:
    key: "your-256-bit-secret-key-must-be-at-least-32-characters-long"
spring:

  application:
    name: tempo-rise-api

  datasource:
    url: jdbc:postgresql://localhost:5432/temporise
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: db/changelog/master.yaml

    #properties:
      #hibernate:
       # default_schema: public
    #  autoconfigure:
    #    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    #  security:
    #    basic:
    #      enabled: false
    #    user:
    #      name:
    #      password:
#  mybatis:
#    mapperLocations=classpath*:**/xml/*:
#      xml: