
services:
  postgres:
    image: postgres:13.10
    container_name: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "temporise", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    #network_mode: "host"  # Utilisation du réseau hôte
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=postgres
      - APP_DB_PASS=postgres
      - APP_DB_NAME=temporise
      - POSTGRES_DB=temporise #the solution here
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      mynetwork:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    #network_mode: "host"  # Utilisation du réseau hôte
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"  # Remplacez par votre adresse e-mail
      PGADMIN_DEFAULT_PASSWORD: "password"       # Remplacez par votre mot de passe
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5099:80"
    networks:
      mynetwork:
volumes:
  pgadmin_data:
networks:
  mynetwork: